### ISSUE TITLE
[Feature request] helm chart

### ISSUE THREAD

**Issue by klml** [it-at-m/ad2image#9]
ad2image runs as container, very well on kuberentes/openshift. Currently only [running-as-a-container-standalone](https://github.com/it-at-m/ad2image#running-as-a-container-standalone) ist documented.

For an easy kuberentes/openshift deploy, a helm chart would be useful.

**Describe the solution you'd like**
* helm chart 

**Describe alternatives you've considered**
kustomize (we are using internally)

**Comment by eidottermihi** [comment]
Things to consider when implementing a Helm chart:

- all [Configuration properties](https://github.com/it-at-m/ad2image#configuration) should be configurable via values.yaml
- Configuration props which are best handled as `Secrets` (AD/EWS credentials) should be optionally configurable via `*.existingSecret`s in values.yaml (see [dependabot-gitlab Chart for an example](https://gitlab.com/dependabot-gitlab/chart#values))
- Image Repo and Tag should be configurable via values.yaml
- generation of an `Ingress` (plain Kubernetes) or `Route` (OpenShift) should be configurable via values.yaml
- custom Cache configuration should be configurable via values.yaml (e.g. `cache.existingConfigMap` which must contain a custom ehcache.xml)

**Comment by eidottermihi** [comment]
Due to Best Practice the helm chart will be developed and published in a seperate repository: https://github.com/it-at-m/ad2image-helm-chart
